from pybtex.backends import BaseBackend
from re import Pattern
from typing import (
    Any,
    Iterator,
    Optional,
    Union, List, Iterable, Tuple, Type,
)


def ensure_text(value: Any) -> BaseText: ...


def str_repr(string: str) -> str: ...


class BaseText:
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: BaseText) -> bool: ...
    def __ne__(self, other: BaseText) -> bool: ...
    def __len__(self) -> int: ...
    def __contains__(self, item: Union[BaseText, str]) -> bool: ...
    def __getitem__(self, index: Union[slice, int]) -> BaseText: ...
    def __add__(self, other: Union[BaseText, str]) -> BaseText: ...
    def append(self, text: Union[BaseText, str]) -> BaseText: ...
    def join(self, parts: Iterable[Union[BaseText, str]]) -> BaseText: ...
    def split(
        self,
        sep: Optional[Union[str, Pattern]] = ...,
        keep_empty_parts: Optional[bool] = ...
    ) -> Iterator[BaseText]: ...
    def abbreviate(self) -> BaseText: ...
    def startswith(self, prefix: str) -> bool: ...
    def endswith(self, suffix: str) -> bool: ...
    def isalpha(self) -> bool: ...
    def add_period(self, period: Union[BaseText, str] = ...) -> BaseText: ...
    def lower(self) -> BaseText: ...
    def upper(self) -> BaseText: ...
    def capfirst(self) -> BaseText: ...
    def capitalize(self) -> BaseText: ...
    def render(self, backend: BaseBackend) -> Any: ...
    def render_as(self, backend_name: str) -> Any: ...
    def _unpack(self) -> Iterator[BaseText]: ...
    def _typeinfo(self) -> Tuple[Optional[Type[BaseText]], Tuple[Any]]: ...


class BaseMultipartText(BaseText):
    info: Tuple[Any]
    parts: List[BaseText]
    length: int
    def __init__(self, *parts: Union[BaseText, str]): ...
    def _create_similar(
        self,
        parts: Iterable[Union[BaseText, str]]
    ) -> BaseMultipartText: ...
    def _merge_similar(
        self,
        parts: Iterable[BaseMultipartText]
    ) -> Iterator[BaseText]: ...
    def _slice_beginning(
        self,
        slice_length: int
    ) -> BaseMultipartText: ...
    def _slice_end(
        self,
        slice_length: int
    ) -> BaseMultipartText: ...
    def _typeinfo(self) -> Tuple[Type[BaseMultipartText], Tuple[Any]]: ...


class HRef(BaseMultipartText):
    def __init__(self, url: Union[BaseText, str], *args: Union[BaseText, str]): ...


class Protected(BaseMultipartText): ...


class String(BaseText):
    value: str
    def __init__(self, *parts: str): ...


class Symbol(BaseText):
    def __init__(self, name: str): ...


class Tag(BaseMultipartText):
    def __init__(self, name: str, *args: Union[BaseText, str]): ...


class Text(BaseMultipartText):
    @classmethod
    def from_latex(cls, latex: str) -> Text: ...
